apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
  namespace: airflow
data:
  GIT_SYNC_USERNAME: c3NoYXJtYTM=
  GIT_SYNC_PASSWORD: Z2l0aHViX3BhdF8xMUJPR0ZVQkEwWFFaYXZ4dUpPZDlSX3Q5S3d6T3VUREhjSnRHbFU4RnJpWEttQUIzTUg4czBLVHU4UWZhWUdPZ25SQVlSWVBSTkxma3R0SE1X
  GITSYNC_USERNAME: c3NoYXJtYTM=
  GITSYNC_PASSWORD: Z2l0aHViX3BhdF8xMUJPR0ZVQkEwWFFaYXZ4dUpPZDlSX3Q5S3d6T3VUREhjSnRHbFU4RnJpWEttQUIzTUg4czBLVHU4UWZhWUdPZ25SQVlSWVBSTkxma3R0SE1X