apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-ksa-full-access
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps","persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-ksa-full-access-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: spark-ksa
    namespace: default
roleRef:
  kind: Role
  name: spark-ksa-full-access
  apiGroup: rbac.authorization.k8s.io
